### ISSUE TITLE
Would like to add this crate to "Crates You Should Know" section of rust+wasm book...

### ISSUE THREAD

**Issue by fitzgen** [iamcodemaker/console_log#1]
Are you OK with that?

Also, it would be good to set up dependabot for this repo to stay on top of `web-sys` updates.

Interested in hearing back,

Nick

**Comment by iamcodemaker** [comment]
I'm fine with that. I'll look into dependabot.

**Comment by iamcodemaker** [comment]
Dependabot configured, thanks for the suggestion.

**Comment by fitzgen** [comment]
Added! https://github.com/rustwasm/book/commit/cde26ad18895984504206b397f462476e95f2998
