### ISSUE TITLE
wasm-logger

### ISSUE THREAD

**Issue by theduke** [iamcodemaker/console_log#3]
Hey, this seems to provide exactly the same functionality as https://crates.io/crates/wasm-logger.

Did you not know about that crate or is there something that's handled differently in console_log?

I always try to advocate for lack of duplication where possible.

**Comment by iamcodemaker** [comment]
I had no idea about that crate. I'll update the readme to link there.

**Comment by iamcodemaker** [comment]
Readme updated.

I briefly looked over wasm-logger. It appears to be slightly more extensive than this library in that it formats the log messages and does some filtering based on the log target. It also swaps the trace and debug levels, mapping `trace` to `console.log()` and `debug` to `console.debug()` which I think is incorrect. Edit: submitted a PR for that.
