### ISSUE TITLE
Configure level for specific crate

### ISSUE THREAD

**Issue by MarcAntoine-Arnaud** [iamcodemaker/console_log#9]
I wanna to know if it's possible to init the logger with specific level for a crate ?

Something like: https://docs.rs/env_logger/0.10.0/env_logger/struct.Builder.html#method.filter_module

Thank you very much.
Marc-Antoine

**Comment by iamcodemaker** [comment]
This is possible, but you have to use the [fern](https://docs.rs/fern/latest/fern/struct.Dispatch.html#method.level_for) crate's [level_for](https://docs.rs/fern/latest/fern/struct.Dispatch.html#method.level_for) filter to do this with console_log. The [console_log::log](https://docs.rs/console_log/0.2.0/console_log/fn.log.html) can be passed to fern's chain method. See the [console_log::log](https://docs.rs/console_log/0.2.0/console_log/fn.log.html#example) docs for an example.
